#### import the numpy package under the name `np`

In [1]:
import numpy as np

#### print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.18.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### find the memory size of any array

In [4]:
Z = np.zeros((10, 10))
print(f'{Z.size}(size) * {Z.itemsize}(itemsize) = {Z.size * Z.itemsize} bytes')

100(size) * 8(itemsize) = 800 bytes


#### get the documentation of the numpy add function from the command line

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### create a null vector of size 10 but the fifth value which is 1

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### create a vector with values ranging from 10 to 49

In [7]:
Z = np.arange(10, 49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### reverse a vector(first element becomes last)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### create a 3*3 matrix with values ranging from 0 to 8

In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### create a 3*3 identity matrix

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### create a 3\*3\*3 array with random values

In [12]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.10945239 0.64274731 0.25394643]
  [0.49077596 0.88780473 0.36145147]
  [0.36588843 0.39702217 0.85431301]]

 [[0.08757202 0.58505572 0.24553159]
  [0.51411546 0.97107323 0.74135664]
  [0.82517412 0.44402866 0.59165294]]

 [[0.69343948 0.70224561 0.34656351]
  [0.39767013 0.37883823 0.08467605]
  [0.31184758 0.30202739 0.40066233]]]


#### create a 10*10 array with random values and find the miminum and maximum values

In [13]:
Z = np.random.random((10, 10))
zMin, zMax = Z.min(), Z.max()
print(zMin, zMax)

0.008192347956450186 0.9982178633761722


#### create a random vector of size 30 and find the mean value

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.44640749805876284


#### create a 2d array with 1 on the border and 0 inside

In [15]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### add a border (filled with 0's) around an existing array

In [16]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### the result of the following expression

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### create a 5*5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### create a 8*8 matrix and fill it with a checkerboard pattern

In [20]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### create a checkerboard 8*8 matrix using the tile function

In [22]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### normalize a 5*5 random matrix

In [23]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-1.83778341  0.67576971 -0.26706579  0.72742937 -1.03131632]
 [ 0.76586061  0.86519299 -0.97994279  0.89083701  1.23464445]
 [-0.03398324 -0.83228492  0.90063992  0.70993978  1.17479834]
 [-1.68699877  0.56990627 -0.26452089 -1.72403096  0.12661012]
 [-1.56476675 -0.87839627  0.69790523  0.80472053  0.95683579]]


#### create a customer dtype that describes a color as four unsigned bytes (RGBA)

In [24]:
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-24-105de449da8b>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1),


#### multiply a 5*3 matrix by a 3*2 matrix (real matrix product)

In [25]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
Z = np.ones((5, 3)) @ np.ones((3, 2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### given a 1d array, negate all elements which are between 3 and 8, in place

In [27]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### the output of the following script

In [28]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### consider an integer vector Z, which of these expressions are legal

In [29]:
# Z ** Z
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# Z<Z>Z

[  0   1   2   4   0   0   0   0 128 256 512]
[False False False False  True  True  True  True False False False]
[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
  0. +8.j  0. +9.j  0.+10.j]
[ 0.  1.  2.  3. -4. -5. -6. -7.  8.  9. 10.]


#### the result of the following expressions

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-30-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-30-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### round away from zero a float array

In [31]:
Z = np.random.uniform(-10, +10, 10)
print(Z)

print(np.copysign(np.ceil(np.abs(Z)), Z))

# more readable but less efficient
print(np.where(Z > 0, np.ceil(Z), np.floor(Z)))

[-7.60486952 -9.79473158 -0.70655942 -0.99508168  0.03289389  6.39972534
 -5.13941673 -9.32060059 -5.82071101 -5.73594312]
[ -8. -10.  -1.  -1.   1.   7.  -6. -10.  -6.  -6.]
[ -8. -10.  -1.  -1.   1.   7.  -6. -10.  -6.  -6.]


#### find common values between two arrays

In [32]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(Z1, '\n', Z2)
print(np.intersect1d(Z1, Z2))

[6 0 8 1 6 6 1 5 2 2] 
 [3 9 3 8 5 8 9 6 5 5]
[5 6 8]


#### ignore all numpy warnings(not recommended)

In [33]:
# suicide mode on
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0

# back to sanity
_ = np.seterr(**defaults)

# equivalently with a context manager
with np.errstate(all='ignore'):
    np.arange(3) / 0

#### is the following expressions true

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-34-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### get the dates of yesterday, today and tomorrow

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-08 2020-08-09 2020-08-10


#### get all dates corresponding to the month of July 2016

In [36]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### compute ((A+B)*(-A/2)) in place (without copy)?

In [37]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]


#### extract the integer part of a random array of positive numbers using 4 different methods

In [38]:
Z = np.random.uniform(0, 10, 10)
print(Z)
print(Z - Z % 1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0.10210522 2.9143143  4.02215434 8.93944769 4.52720769 3.601787
 1.13624783 9.4181346  9.37699242 2.73881414]
[0. 2. 4. 8. 4. 3. 1. 9. 9. 2.]
[0. 2. 4. 8. 4. 3. 1. 9. 9. 2.]
[0. 2. 4. 8. 4. 3. 1. 9. 9. 2.]
[0 2 4 8 4 3 1 9 9 2]
[0. 2. 4. 8. 4. 3. 1. 9. 9. 2.]


#### create a 5*5 matrix with row values ranging from 0 to 4

In [39]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### consider a generator function the generates 10 integers and use it to build an array

In [40]:
def generate():
    for x in range(10):
        yield x


Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### create a vector of size 10 with values ranging from 0 to 1, both excluded

In [41]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### create a random vector of size 10 and sort it

In [42]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.23631474 0.5552401  0.60830934 0.70050191 0.72689293 0.80783152
 0.90617533 0.9142921  0.91574284 0.95762496]


#### sum a small array faster than np.sum

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### consider two random array A and B, check if they are equal

In [44]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A, B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A, B)
print(equal)

False
False


#### make an array immutable(read-only)

In [45]:
Z = np.zeros(10)
# Z.flags.writeable = False
Z[0] = 1

#### consider a random 10*2 matrix representing cartesial coordinates, convert them to polar coordinates

In [46]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.51379832 0.56164469 0.99149391 0.59082456 0.21903673 0.60446536
 0.58519181 0.29608336 0.93513305 0.75680465]
[1.47277934e+00 1.80282437e-01 1.13964876e+00 1.56425207e-01
 1.11644309e-03 3.49336438e-01 4.19405468e-01 1.25323037e+00
 4.58522229e-01 7.13130201e-01]


 #### create random vector of size 10 and replace the maximum value by 0

In [47]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.42759693 0.81109084 0.77741291 0.14390503 0.18465748 0.65977485
 0.20525051 0.4206554  0.07804719 0.        ]


#### create a structured array with x and y coordinates covering the [0,1]\*[0,1] area

In [48]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### print the minimum and maximum representable value for each numpy scalar type

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### print all the values of an array

In [51]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16, 16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### find the closest value (to a given scalar) in a vector

In [52]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0, 100)
print(v)
index = (np.abs(Z - v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
23.95837961395526
24


#### create a structured array representing a position (x,y) and a color (r,g,b)

In [53]:
Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),
                  ('color', [('r', float, 1), ('g', float, 1),
                             ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-53-62fe69470798>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),


#### consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [54]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

# Much faster with scipy
import scipy
import scipy.spatial

D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[0.         0.24012123 0.63271046 0.29882885 0.57932252 0.64628912
  0.14855674 0.68388932 0.79644375 0.20203083]
 [0.24012123 0.         0.75862032 0.24431922 0.78366392 0.78613006
  0.23627242 0.54792287 0.89113107 0.07200907]
 [0.63271046 0.75862032 0.         0.54929    0.31580444 0.05317783
  0.53236705 0.71864061 0.18682491 0.68661156]
 [0.29882885 0.24431922 0.54929    0.         0.65183316 0.58532356
  0.16391415 0.38779139 0.66086643 0.18215475]
 [0.57932252 0.78366392 0.31580444 0.65183316 0.         0.27505864
  0.55212053 0.94004248 0.4832392  0.71832185]
 [0.64628912 0.78613006 0.05317783 0.58532356 0.27505864 0.
  0.55555929 0.76962302 0.21113341 0.71427198]
 [0.14855674 0.23627242 0.53236705 0.16391415 0.55212053 0.55555929
  0.         0.55110693 0.6802204  0.16735758]
 [0.68388932 0.54792287 0.71864061 0.38779139 0.94004248 0.76962302
  0.55110693 0.         0.73287643 0.52067533]
 [0.79644375 0.89113107 0.18682491 0.66086643 0.4832392  0.21113341
  0.6802204  0.73287

#### convert a float (32 bits) array into an integer (32 bits) in place

In [55]:
Z = (np.random.rand(10) * 100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[32 16 90 96 21 47 72 37 80 89]


#### read the following file

In [56]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6, -1, -2, 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -2  7  8]
 [-1 -1  9 10 11]]


####  the equivalent of enumerate for numpy arrays

In [57]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### generate a generic 2D Gaussian-like array

In [58]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
print(X, '\n\n', Y)
print()
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2)))
print(G)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### randomly place p elements in a 2D array

In [59]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n * n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### subtract the mean of each row of a matrix

In [60]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.0269509  -0.40389984 -0.23345087  0.42079547  0.39283917 -0.00254752
   0.38251608 -0.34661333 -0.21578566  0.0330974 ]
 [ 0.33513204  0.23254416 -0.25934012  0.06930111 -0.23983211  0.18273211
   0.0028465   0.310435   -0.33630093 -0.29751775]
 [-0.48493874 -0.38264604 -0.47002403 -0.09850395  0.28085159  0.20979978
   0.45680603  0.12301111 -0.09372882  0.45937307]
 [ 0.22447643 -0.41167769 -0.13663663 -0.03747121  0.37283676  0.17305269
   0.01080496 -0.02889466 -0.24467413  0.07818348]
 [ 0.22033654  0.20403661 -0.46388528 -0.40540461 -0.05501773  0.22270345
   0.08452468  0.17723662  0.36048655 -0.34501684]]


#### sort an array by the nth column

In [61]:
Z = np.random.randint(0, 10, (3, 3))
print(Z)
print(Z[Z[:, 1].argsort()])

[[4 4 7]
 [6 1 6]
 [7 4 7]]
[[6 1 6]
 [4 4 7]
 [7 4 7]]


#### tell if a given 2D array has null columns

In [62]:
Z = np.random.randint(0, 3, (3, 10))
print((~Z.any(axis=0)).any())

False


#### find the nearest value from a given value in an array

In [63]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5064099574954383


#### considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator

In [64]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
print(it)
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### create an array class that has a name attribute

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")


Z = NamedArray(np.arange(10), "range_10")
print(Z.name)
print(Z.info)

range_10
no name


#### consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [66]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[4. 4. 5. 4. 1. 1. 1. 3. 2. 5.]
[7. 7. 9. 7. 1. 1. 1. 5. 3. 9.]


#### accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [67]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [68]:
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### considering a four dimensions array, how to get sum over the last two axis at once

In [69]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2, -1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1, )).sum(axis=-1)
print(sum)

[[58 42 56 49]
 [59 53 41 46]
 [46 53 64 35]]
[[58 42 56 49]
 [59 53 41 46]
 [46 53 64 35]]


#### considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices

In [70]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.51825246 0.54108366 0.50159082 0.49682603 0.54521443 0.37963189
 0.48168509 0.54043962 0.49650732 0.42041735]
0    0.518252
1    0.541084
2    0.501591
3    0.496826
4    0.545214
5    0.379632
6    0.481685
7    0.540440
8    0.496507
9    0.420417
dtype: float64


#### get the diagonal of a dot product

In [71]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.90526075, 0.96769578, 1.37274488, 0.5595075 , 2.48878418])

#### consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value

In [72]:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))
Z0[::nz + 1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)

In [73]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### swap two rows of an array

In [74]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [75]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 0, 55) ( 0, 60) ( 2, 39) ( 2, 55) (18, 18) (18, 19) (18, 46) (18, 89)
 (19, 31) (19, 80) (24, 37) (24, 97) (28, 58) (28, 70) (31, 80) (37, 97)
 (39, 55) (42, 44) (42, 61) (44, 61) (46, 89) (50, 91) (50, 92) (55, 60)
 (58, 70) (66, 77) (66, 91) (77, 91) (91, 92)]


#### given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C

In [76]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### compute averages using a sliding window over an array

In [77]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n


Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [78]:
from numpy.lib import stride_tricks


def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)


Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### negate a boolean, or to change the sign of a float inplace

In [79]:
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out=Z)

array([-0.91628623, -0.62645398,  0.53602247, -0.42618039, -0.00732033,
       -0.80719989, -0.0608813 , -0.03388977, -0.29806395,  0.55657202,
       -0.78452292,  0.79778713,  0.15488694,  0.23456234, -0.5426173 ,
        0.04297359, -0.14745857,  0.97924917, -0.14609973, -0.29759028,
       -0.00279953, -0.19363356, -0.85121705, -0.47839472, -0.71274194,
       -0.69468646,  0.43816579, -0.09566499, -0.31940932, -0.64814779,
        0.52990043, -0.3017982 , -0.00988581,  0.2643675 , -0.29805314,
       -0.64277969, -0.59855066, -0.87522677, -0.73578027, -0.82429745,
        0.6209867 ,  0.12292213,  0.85683346,  0.95604986,  0.37080077,
        0.02836917, -0.77982323,  0.59743208,  0.17806955, -0.5819153 ,
       -0.62393764, -0.78304576,  0.03136544,  0.16016835,  0.86242045,
        0.14975283, -0.41317784, -0.09842405,  0.31281509,  0.99856776,
        0.92150576,  0.55903997, -0.58683822,  0.1274707 ,  0.20392496,
        0.75374381, -0.43660848, -0.82812416, -0.73765073, -0.60

#### consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])

In [80]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] +
          (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[ 6.90868644  3.40044301  3.66854075  2.77498904  9.8661753   0.61714563
  0.59659635  7.57035645  9.73109346 10.6069513 ]


#### consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])

In [81]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[5.28860222e+00 8.02281701e-01 2.41135462e+00 1.43765008e+01
  1.72173375e+01 1.53690912e+01 2.21661278e+00 1.09647849e+00
  9.14684632e+00 1.38069104e+01]
 [5.28401895e+00 1.12520073e+01 1.32079426e+01 2.48243620e+00
  5.73163403e+00 6.21845611e+00 1.07592010e+01 9.51814478e+00
  4.21634047e+00 9.56043945e+00]
 [4.85335493e+00 1.12139015e+00 3.00966196e+00 4.02066161e+00
  6.91723548e+00 5.55059253e+00 1.09264599e+00 6.45359562e-01
  6.98495684e-01 5.62750200e+00]
 [1.41895756e+01 2.32936376e+00 4.47969627e+00 5.61171183e+00
  2.63217828e+00 3.38984106e+00 9.35793627e-01 6.86602120e-01
  6.72836471e+00 1.51530513e+00]
 [6.40752364e+00 1.08271802e+01 1.28115061e+01 1.38520270e+00
  4.62464345e+00 5.08144143e+00 1.01928338e+01 9.10670061e+00
  3.10412220e+00 8.45965290e+00]
 [1.93075828e+00 5.94415986e-02 1.86190632e+00 7.11021102e+00
  9.95714165e+00 8.27597214e+00 4.85164465e-01 1.74796509e+00
  2.76137257e+00 7.57417530e+00]
 [2.25444076e-01 2.95185237e+00 1.21264831e+00 9.17261927e

#### consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a 'fill' value when necessary)

In [82]:
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape), )).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P - Rs // 2)
Z_stop = (P + Rs // 2) + Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 7 0 2 2 4 2 1 9 4]
 [7 8 3 6 1 6 4 6 2 1]
 [1 5 7 0 2 8 6 3 0 4]
 [5 4 5 7 9 5 6 2 4 6]
 [4 2 3 4 4 3 1 8 3 4]
 [4 2 1 7 6 2 5 3 9 6]
 [9 3 0 5 4 6 6 3 7 0]
 [8 9 5 5 2 7 9 4 4 2]
 [3 5 9 9 9 8 3 6 0 5]
 [0 1 2 9 8 4 0 9 9 1]]
[[0 0 0 0 0]
 [0 9 7 0 2]
 [0 7 8 3 6]
 [0 1 5 7 0]
 [0 5 4 5 7]]


<ipython-input-82-2d794467d588>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [83]:
Z = np.arange(1, 15, dtype=np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### compute a matrix rank

In [84]:
Z = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(Z)  # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### find the most frequent value in an array

In [85]:
Z = np.random.randint(0, 10, 50)
print(np.bincount(Z).argmax())

5


#### extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [86]:
Z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (Z.shape[0] - 3)
j = 1 + (Z.shape[1] - 3)
C = stride_tricks.as_strided(Z,
                             shape=(i, j, n, n),
                             strides=Z.strides + Z.strides)
print(C)

[[[[2 0 1]
   [0 2 4]
   [1 2 4]]

  [[0 1 0]
   [2 4 3]
   [2 4 4]]

  [[1 0 0]
   [4 3 2]
   [4 4 0]]

  [[0 0 3]
   [3 2 0]
   [4 0 0]]

  [[0 3 0]
   [2 0 1]
   [0 0 3]]

  [[3 0 4]
   [0 1 3]
   [0 3 3]]

  [[0 4 3]
   [1 3 0]
   [3 3 2]]

  [[4 3 1]
   [3 0 0]
   [3 2 0]]]


 [[[0 2 4]
   [1 2 4]
   [1 2 3]]

  [[2 4 3]
   [2 4 4]
   [2 3 3]]

  [[4 3 2]
   [4 4 0]
   [3 3 4]]

  [[3 2 0]
   [4 0 0]
   [3 4 2]]

  [[2 0 1]
   [0 0 3]
   [4 2 0]]

  [[0 1 3]
   [0 3 3]
   [2 0 3]]

  [[1 3 0]
   [3 3 2]
   [0 3 1]]

  [[3 0 0]
   [3 2 0]
   [3 1 0]]]


 [[[1 2 4]
   [1 2 3]
   [1 2 2]]

  [[2 4 4]
   [2 3 3]
   [2 2 1]]

  [[4 4 0]
   [3 3 4]
   [2 1 1]]

  [[4 0 0]
   [3 4 2]
   [1 1 3]]

  [[0 0 3]
   [4 2 0]
   [1 3 2]]

  [[0 3 3]
   [2 0 3]
   [3 2 0]]

  [[3 3 2]
   [0 3 1]
   [2 0 0]]

  [[3 2 0]
   [3 1 0]
   [0 0 0]]]


 [[[1 2 3]
   [1 2 2]
   [2 0 4]]

  [[2 3 3]
   [2 2 1]
   [0 4 3]]

  [[3 3 4]
   [2 1 1]
   [4 3 2]]

  [[3 4 2]
   [1 1 3]
   [3 2 1]]

  [[4 2 0]
   

#### create a 2D array subclass such that Z[i,j] == Z[j,i] 

In [87]:
# Note: only works for 2d array and value setting using indices


class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)


S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print(S)

[[ 0 12  8  3 12]
 [12  1  9  2 13]
 [ 8  9  7 42 11]
 [ 3  2 42  6  4]
 [12 13 11  4  9]]


#### consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [88]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### consider a 16x16 array, how to get the block-sum (block size is 4x4)

In [89]:
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k),
                    axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### implement the Game of Life using numpy arrays

In [90]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] + Z[1:-1, 0:-2] +
         Z[1:-1, 2:] + Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0

#### get the n largest values of an array

In [91]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print(Z[np.argsort(Z)[-n:]])

# Fast
print(Z[np.argpartition(-Z, n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### create a record array from a regular array

In [93]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [94]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.82 s ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
340 ms ± 4.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
194 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B

In [95]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[0 1 4 6 7]


#### considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [96]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1), :]
print(U)

[[1 4 4]
 [2 2 4]
 [2 1 4]
 [1 0 1]
 [0 0 0]
 [4 3 0]
 [0 2 0]
 [0 3 1]
 [1 3 3]
 [0 4 2]]
[[1 4 4]
 [2 2 4]
 [2 1 4]
 [1 0 1]
 [4 3 0]
 [0 2 0]
 [0 3 1]
 [1 3 3]
 [0 4 2]]
[[1 4 4]
 [2 2 4]
 [2 1 4]
 [1 0 1]
 [4 3 0]
 [0 2 0]
 [0 3 1]
 [1 3 3]
 [0 4 2]]


#### convert a vector of ints into a matrix binary representation

In [97]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(B[:, ::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### given a two dimensional array, how to extract unique rows

In [98]:
Z = np.random.randint(0, 2, (6, 3))
T = np.ascontiguousarray(Z).view(
    np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [99]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

np.einsum('i->', A)  # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)  # np.inner(A, B)
np.einsum('i,j->ij', A, B)  # np.outer(A, B)

array([[5.29764400e-03, 4.32972290e-02, 6.65757161e-02, 2.44583092e-02,
        5.29088201e-02, 1.17712948e-02, 6.00529917e-02, 6.62958847e-02,
        1.34740295e-02, 3.25205487e-02],
       [7.93267157e-03, 6.48331026e-02, 9.96902190e-02, 3.66237773e-02,
        7.92254620e-02, 1.76262911e-02, 8.99231167e-02, 9.92712004e-02,
        2.01759595e-02, 4.86961435e-02],
       [7.61938838e-04, 6.22726637e-03, 9.57531759e-03, 3.51774028e-03,
        7.60966289e-03, 1.69301800e-03, 8.63718036e-03, 9.53507056e-03,
        1.93791550e-03, 4.67729978e-03],
       [1.14493957e-02, 9.35750128e-02, 1.43885039e-01, 5.28598862e-02,
        1.14347815e-01, 2.54404054e-02, 1.29787970e-01, 1.43280261e-01,
        2.91203968e-02, 7.02841923e-02],
       [3.18392573e-02, 2.60219753e-01, 4.00125293e-01, 1.46996363e-01,
        3.17986173e-01, 7.07464079e-02, 3.60923206e-01, 3.98443484e-01,
        8.09799779e-02, 1.95451057e-01],
       [6.68441624e-02, 5.46312097e-01, 8.40033415e-01, 3.08607976e-01,
   

#### considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [100]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)  # integrate path
r_int = np.linspace(0, r.max(), 200)  # regular spaced path
x_int = np.interp(r_int, r, x)  # integrate path
y_int = np.interp(r_int, r, y)

#### given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [102]:
X = np.random.randn(100)  # random 1D array
N = 1000  # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.09039749  0.29258777]
