# Preliminaries

- Numpy
- pandas
- matplotlib
- IPython and Jupyter
- SciPy
- scikit-learn
- statsmodels

# Python Language Basic, IPython, and Jupyter Notebook

In [1]:
import numpy as np
data = {i: np.random.randn() for i in range(7)}
data?

Type:        dict
String form: {0: 0.06940783203633408, 1: 0.34411995647415683, 2: -2.087116041531572, 3: -0.3726461620146253, 4: -1.1069746607231392, 5: -0.2905387918080224, 6: -1.1794699138135767}
Length:      7
Docstring:  
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)


In [2]:
b = [1, 2, 3]
b?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [3]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [4]:
def add_numbers(a, b):
    """
    Add two numbers together
    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

In [5]:
add_numbers?

Signature: add_numbers(a, b)
Docstring:
Add two numbers together
Returns
-------
the_sum : type of arguments
File:      d:\workspace\vital\notebook\learn more study less\1 acquire\python\data analysis\<ipython-input-4-5447cfd50127>
Type:      function


In [6]:
add_numbers??

Signature: add_numbers(a, b)
Source:   
def add_numbers(a, b):
    """
    Add two numbers together
    Returns
    -------
    the_sum : type of arguments
    """
    return a + b
File:      d:\workspace\vital\notebook\learn more study less\1 acquire\python\data analysis\<ipython-input-4-5447cfd50127>
Type:      function


In [7]:
np.*load*?

np.__loader__
np.load
np.loads
np.loadtxt

In [8]:
a = np.random.randn(100, 100)
%timeit np.dot(a, a)

130 µs ± 9.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%debug?

Docstring:
::

  %debug [--breakpoint FILE:LINE] [statement [statement ...]]

Activate the interactive debugger.

This magic command support two ways of activating debugger.
One is to activate debugger before executing code.  This way, you
can set a break point, to step through the code from the point.
You can use this mode by giving statements to execute and optionally
a breakpoint.

The other one is to activate debugger in post-mortem mode.  You can
activate this mode simply running %debug without any argument.
If an exception has just occurred, this lets you inspect its stack
frames interactively.  Note that this will always work only on the last
traceback that occurred, so you must call this quickly after an
exception that you wish to inspect has fired, because if another one
occurs, it clobbers the previous one.

If you want IPython to automatically do this on every exception, see
the %pdb magic for more details.

.. versionchanged:: 7.3
    When running code, user variables are n

In [10]:
%pwd

'd:\\WorkSpace\\vital\\notebook\\learn more study less\\1 Acquire\\python\\data analysis'

In [11]:
foo = %pwd

In [12]:
foo

'd:\\WorkSpace\\vital\\notebook\\learn more study less\\1 Acquire\\python\\data analysis'

In [13]:
%matplotlib

Using matplotlib backend: TkAgg


In [14]:
%matplotlib inline

# Build-in Data Structures, Functions, and Files

# Numpy Basics: Arrays and Vectorized Computation

- ndarray
- Mathematical funcations
- tools for reading/writing array data
- linear algebra

In [15]:
import numpy as np

In [16]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [17]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 24.9 ms


In [18]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.2 s


## The Numpy ndarray: A Multidimensional Array Object

In [19]:
data = np.random.randn(2, 3)
data

array([[ 0.24583916, -1.05003507,  0.26289242],
       [-1.39564883, -0.01698541,  0.45255397]])

In [20]:
data * 10

array([[  2.45839155, -10.50035073,   2.62892425],
       [-13.95648829,  -0.16985406,   4.52553975]])

In [21]:
data + data

array([[ 0.49167831, -2.10007015,  0.52578485],
       [-2.79129766, -0.03397081,  0.90510795]])

In [22]:
data.shape

(2, 3)

In [23]:
data.dtype

dtype('float64')

### Creating ndarrays

In [24]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 4)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Getting Started with pandas

# Data Loading, Storage, and File Formats

# Data Cleaning and Preparation

# Data Wrangling: Join, Combine, and Reshape

# Plotting and Visualization

# Data Aggregation and Group Operations

# Time Series

# Advanced pandas

# Introduction to Modeling Libraries in Python

# Data Analysis Examples

# Advanced Numpy

# More on the IPython System

# 